
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  student: 'student',
  recruiter: 'recruiter'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const ApplicationStatus = {
  pending: 'pending',
  accepted: 'accepted',
  rejected: 'rejected'
} as const

export type ApplicationStatus = (typeof ApplicationStatus)[keyof typeof ApplicationStatus]
